"""Position pyramiding (scaling into winning positions).

This module provides utilities for adding to a winning position in stages as
it moves favorably, using either fixed price/ATR increments or a decreasing
add-on size ("scaling in") to manage risk as the position grows.

Example:
    >>> from imst_quant.trading.position_pyramiding import generate_pyramid_levels
    >>> levels = generate_pyramid_levels(
    ...     entry_price=100.0, atr=2.0, max_adds=3, atr_multiplier=1.5
    ... )
    >>> [lvl.trigger_price for lvl in levels]
"""

from dataclasses import dataclass
from typing import Literal

Direction = Literal["long", "short"]


@dataclass
class PyramidLevel:
    """A single scale-in level for a pyramided position.

    Attributes:
        level: 1-indexed add-on number (1 = first add after initial entry).
        trigger_price: Price at which this add-on should be executed.
        size_fraction: Fraction of the *original* position size to add at
            this level (decreasing by default to reduce risk as the
            position grows).
        cumulative_size_fraction: Total position size (as a multiple of the
            original size) after this add-on is executed.
    """

    level: int
    trigger_price: float
    size_fraction: float
    cumulative_size_fraction: float


def generate_pyramid_levels(
    entry_price: float,
    atr: float,
    max_adds: int = 3,
    atr_multiplier: float = 1.5,
    direction: Direction = "long",
    size_decay: float = 0.5,
) -> list[PyramidLevel]:
    """Generate scale-in trigger levels for pyramiding into a winning trade.

    Each subsequent add-on is triggered ``atr_multiplier * atr`` further in
    the favorable direction from the previous trigger, and sized at
    ``size_decay`` times the previous add-on's size (so risk contribution
    shrinks as the position grows).

    Args:
        entry_price: Initial entry price of the position.
        atr: Average True Range value used to space add-on levels.
        max_adds: Maximum number of scale-in add-ons. Defaults to 3.
        atr_multiplier: ATR multiplier controlling spacing between levels.
            Defaults to 1.5.
        direction: "long" or "short". Defaults to "long".
        size_decay: Multiplier applied to each successive add-on's size
            relative to the previous add-on (e.g. 0.5 halves each add-on).
            Must be in (0, 1]. Defaults to 0.5.

    Returns:
        List of PyramidLevel objects, one per add-on, in trigger order.

    Raises:
        ValueError: If max_adds < 1, atr <= 0, or size_decay not in (0, 1].

    Example:
        >>> levels = generate_pyramid_levels(100.0, atr=2.0, max_adds=2)
        >>> levels[0].trigger_price
        103.0
    """
    if direction not in ("long", "short"):
        raise ValueError(f"direction must be 'long' or 'short', got {direction!r}")
    if max_adds < 1:
        raise ValueError(f"max_adds must be >= 1, got {max_adds}")
    if atr <= 0:
        raise ValueError(f"atr must be positive, got {atr}")
    if not 0 < size_decay <= 1:
        raise ValueError(f"size_decay must be in (0, 1], got {size_decay}")

    sign = 1 if direction == "long" else -1
    step = atr_multiplier * atr

    levels: list[PyramidLevel] = []
    cumulative = 1.0
    add_size = size_decay

    for i in range(1, max_adds + 1):
        trigger_price = entry_price + sign * step * i
        cumulative += add_size
        levels.append(
            PyramidLevel(
                level=i,
                trigger_price=trigger_price,
                size_fraction=add_size,
                cumulative_size_fraction=cumulative,
            )
        )
        add_size *= size_decay

    return levels


def next_pyramid_trigger(
    current_price: float,
    levels: list[PyramidLevel],
    executed_levels: set[int],
    direction: Direction = "long",
) -> PyramidLevel | None:
    """Find the next unexecuted pyramid level that has been triggered by price.

    Args:
        current_price: Latest market price.
        levels: Pyramid levels generated by generate_pyramid_levels.
        executed_levels: Set of level numbers already executed.
        direction: "long" or "short". Defaults to "long".

    Returns:
        The lowest-numbered unexecuted PyramidLevel whose trigger has been
        reached, or None if no new add-on is triggered.

    Example:
        >>> levels = generate_pyramid_levels(100.0, atr=2.0, max_adds=2)
        >>> next_pyramid_trigger(104.0, levels, executed_levels=set())
        PyramidLevel(level=1, ...)
    """
    if direction not in ("long", "short"):
        raise ValueError(f"direction must be 'long' or 'short', got {direction!r}")

    pending = [lvl for lvl in levels if lvl.level not in executed_levels]
    pending.sort(key=lambda lvl: lvl.level)

    for lvl in pending:
        if direction == "long" and current_price >= lvl.trigger_price:
            return lvl
        if direction == "short" and current_price <= lvl.trigger_price:
            return lvl

    return None


def total_position_size(
    base_size: float,
    levels: list[PyramidLevel],
    executed_levels: set[int],
) -> float:
    """Compute total position size after a set of pyramid add-ons.

    Args:
        base_size: Original position size at initial entry.
        levels: Pyramid levels generated by generate_pyramid_levels.
        executed_levels: Set of level numbers that have been executed.

    Returns:
        Total position size as base_size scaled by 1.0 plus the sum of
        size_fraction for each executed level.

    Example:
        >>> levels = generate_pyramid_levels(100.0, atr=2.0, max_adds=2)
        >>> total_position_size(1000.0, levels, {1})
        1500.0
    """
    added_fraction = sum(lvl.size_fraction for lvl in levels if lvl.level in executed_levels)
    return base_size * (1.0 + added_fraction)
